### ISSUE TITLE
About Design tools for HTML game

### ISSUE THREAD

**Issue by qishen** [ahung89/ahung89.github.io#1]
Hi Andrew,
You really made some awesome games! I'm a beginner HTML game developer and I was wondering what kind of design tools you are using to create menu buttons or How-to tutorial picture. I really want to improve my game with beautiful design.

Thanks,

Victor

**Comment by ahung89** [comment]
Hey Victor, thanks for the kind words. Honestly the menu buttons/UI elements in both games were not made with much artistic skill :). For AndrewWorld, I actually used an online logo generator to create all of the text. The background image for the title screen is just a random image from the internet. For Bomb Boy Online, I actually drew the title, buttons, and background in photoshop.

To actually code the UI, I just used the APIs for buttons, etc. provided by Phaser. Nothing too fancy. Let me know if you have any other questions, and good luck with your games!
